# Generated by Django 4.2.27 on 2026-01-11 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('education_level', models.CharField(blank=True, max_length=50)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('university', models.CharField(blank=True, max_length=150)),
                ('preferred_industry', models.CharField(blank=True, max_length=100)),
                ('job_level', models.CharField(blank=True, max_length=50)),
                ('cv', models.FileField(blank=True, upload_to='cvs/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
